### ISSUE TITLE
需要 忽略 socket 错误,  

### ISSUE THREAD

**Issue by xcwen** [TarsPHP/tars-registry#1]
src/client/CommunicatorRegistry.php 
========================================
需要 忽略 socket 错误,  

WARNING:socket_connect(): unable to connect [111]: Connection refused\n\/home\/jim\/vipthink_core\/src\/vendor\/phptars\/tars-registry\/src\/client\/CommunicatorRegistry.php:109

        if (!@\socket_connect($sock, $sIp, $iPort)) {
            @\socket_close($sock);
            throw new \Exception();
        }

        if (!@\socket_write($sock, $requestBuf, strlen($requestBuf))) {
            @\socket_close($sock);
            throw new \Exception();
        }

**Comment by meijing0114** [comment]
不建议忽略，需要这些debug信息。
